# Use the official MySQL image as the base image
FROM mysql:latest

# Set the root password for MySQL
ENV MYSQL_ROOT_PASSWORD=25102004****$

COPY . /cloud.sql /docker-entrypoint-initdb.d/
#docker build -t database